name: Manual CD

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to deploy in PRO'
        required: true

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Load environment variables from .env
        run: |
            set -a
            [ -f app/.env ] && . app/.env
            set +a
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Pull the latest image
        run: | 
          RESPONSE=$(curl -s "https://hub.docker.com/v2/repositories/$REPOSITORY/tags")
          TAGS=$(echo "$RESPONSE" | grep -o "\"name\":\"$IMAGE_TAG-rc[0-9]*\"" | grep -o "$IMAGE_TAG-rc[0-9]*")
          SORTED_TAGS=$(echo "$TAGS" | sort -V)
          LATEST_TAG=$(echo "$SORTED_TAGS" | tail -1)
          docker pull $IMAGE_NAME:$IMAGE_TAG
      - name: Determine the latest release candidate tag
        run: |
          REPOSITORY=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          echo "::set-env name=LATEST_TAG::$LATEST_TAG"
      - name: Pull the latest release candidate image
        run: docker pull $REPOSITORY:$LATEST_TAG
      - name: Tag Docker image with the latest release
        run: docker tag $REPOSITORY:$LATEST_TAG $REPOSITORY:latest
      - name: Push Docker image with the latest release
        run: docker push $REPOSITORY:latest
  # deploy:
