name: CI-PRO

on:
  pull_request:
    branches:
    - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  
jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@main
      - name: Build the Docker image
        run: make build
      - name: Run integration tests
        run: make test-integration    
  publish-image-rc:
    name: Publish release candidate
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@main
      - name: Build the Docker image
        run: make build
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Publish the release candidate
        run: make publish-image-rc      
  publish-image-latest:
    name: Publish latest release
    needs: publish-image-rc
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@main
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Publish the latest release
        run: make publish-image-latest