name: CI-PRO

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'app/.dockerignore'
  
jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@main
      - name: Build the Docker image
        run: make build
      - name: Run integration tests
        run: make test-integration
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}         
      - name: Publish the release candidate Docker image
        if: success()
        run: make publish-image-rc      
  publish-image:
    name: Publish Docker image
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@main
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Publish the latest Docker image
        if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main'
        run: make publish-image-latest    