name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'Makefile'

jobs:
  #checkstyle:
  #  name: Analyze the code
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check out the repository
  #      uses: actions/checkout@v2
  #    - name: Build the Docker image
  #      run: make build
  #    - name: Run checkstyle
  #      run: make pre-commit
#
  #tests:
  #  name: Run tests
  #  needs: checkstyle
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check out the repository
  #      uses: actions/checkout@v2
  #    - name: Build the Docker image
  #      run: make build
  #    - name: Run unit tests
  #      run: make test-unit
  #    - name: Run acceptance tests
  #      run: make test-acceptance
  #    - name: Run integration tests
  #      run: make test-integration        

  publish-release-candidate:
    name: Prepare image and push it to DockerHub
    #needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        
      - name: Create Docker image
        run: make build
      - name: Tag Docker image with the next release candidate
        run: make prepare-image
      - name: Push Docker image as release candidate
        run: make push-image-rc
