name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ci.yml'
      - 'app/**'
      - 'Makefile'

jobs:
  #checkstyle:
  #  name: Analyze the code
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check out the repository
  #      uses: actions/checkout@v2
  #    - name: Build the Docker image
  #      run: make build
  #    - name: Run checkstyle
  #      run: make pre-commit
#
  #tests:
  #  name: Run tests
  #  needs: checkstyle
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Check out the repository
  #      uses: actions/checkout@v2
  #    - name: Build the Docker image
  #      run: make build
  #    - name: Run unit tests
  #      run: make test-unit
  #    - name: Run acceptance tests
  #      run: make test-acceptance
  #    - name: Run integration tests
  #      run: make test-integration        
#
  prepare-image:
    name: Prepare image and tag
    #needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Load environment variables from .env
        run: |
            set -a
            [ -f app/.env ] && . app/.env
            set +a
      - name: Tag Docker image with the next release candidate
        run: |
          set -a
          [ -f app/.env ] && . app/.env
          set +a
          echo "IMAGE_NAME >> $IMAGE_NAME"
          REPOSITORY=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME
          echo "REPOSITORY >> $REPOSITORY"
          RESPONSE=$(curl -s "https://hub.docker.com/v2/repositories/$REPOSITORY/tags")
          echo "RESPONSE >> $RESPONSE"
          TAGS=$( [ -z "$RESPONSE" ] && echo "$IMAGE_TAG-rc0" || echo "$RESPONSE" | grep -o "\"name\":\"$IMAGE_TAG-rc[0-9]*\"" | grep -o "$IMAGE_TAG-rc[0-9]*" )
          echo "TAGS >> $TAGS"
          SORTED_TAGS=$(echo "$TAGS" | sort -V)
          echo "SORTED_TAGS >> $SORTED_TAGS"
          LATEST_TAG=$(echo "$SORTED_TAGS" | tail -1)
          echo "LATEST_TAG >> $LATEST_TAG"
          LATEST_RC=$(echo "$LATEST_TAG" | awk -F. '{print $NF}')
          echo "LATEST_RC >> $LATEST_RC"
          NEXT_RC=$((LATEST_RC + 1))
          echo "NEXT_RC >> $NEXT_RC"
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG-rc$NEXT_RC
  push-image:
    name: Push image as release candidate
    needs: prepare-image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image as release candidate
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG-rc$NEXT_RC
