name: CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/CI.yml'
      - 'app/**'
      - 'Makefile'

jobs:
  checkstyle:
    name: Analyze the code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: make build
      - name: Run checkstyle
        run: make pre-commit

  tests:
    name: Run tests
    needs: checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Build the Docker image
        run: make build
      - name: Run unit tests
        run: make test-unit
      - name: Run acceptance tests
        run: make test-acceptance
      - name: Run integration tests
        run: make test-integration        

  prepare-image:
    name: Prepare image and tag
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Load environment variables from .env
        run: |
            set -a
            [ -f app/.env ] && . app/.env
            set +a
            echo $IMAGE_NAME
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Tag Docker image with the next release candidate
        run: |
          LATEST_RC=$(echo "$IMAGE_TAG" | awk -F. '{print $NF}')
          echo $LATEST_RC
          NEXT_RC=$((LATEST_RC + 1))
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG-rc$NEXT_RC
      - name: Push Docker image as release candidate
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG-rc$NEXT_RC
