name: CD

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release to deploy in PRO'
        required: true

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Publish the latest release
        run: make publish-release
  # deploy:
